<?php


namespace App\Presenters;

use Nette\Application\BadRequestException;
use Nette\Application\Request;

/**
 * Class Error4xxPresenter
 * @package App\Presenters
 */
final class Error4xxPresenter extends BasePresenter
{
    /**
     * Error4xxPresenter constructor.
     * @param bool $startupInit
     */
    public function __construct(bool $startupInit = false)
    {
        parent::__construct($startupInit);
    }

    /**
     * @return array
     */
    public function formatTemplateFiles(): array { return array(); }

    /**
     * @throws BadRequestException
     */
    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if (!$this->getRequest()->isMethod(Request::FORWARD)) $this->error();
    }

    /**
     * @param BadRequestException $exception
     */
    public function renderDefault(BadRequestException $exception) {
        $file = __DIR__ . "ErrorModule/{$exception->getCode()}.latte";
        $this->template->setFile(is_file($file) ? $file : __DIR__ . '/ErrorModule/4xx.latte');
        $this->template->exception = $exception;
    }
}